version: '3.8'

services:
  db:
    build: .
    ports:
      - "8082:8082"
    volumes:
      - db-data:/opt/practice-4/out
    command: ["db"]
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:8082/health"]
      interval: 10s
      timeout: 5s
      retries: 3

  server1:
    build: .
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
    command: ["server"]
    depends_on:
      db:
        condition: service_healthy

  server2:
    build: .
    ports:
      - "8081:8080"
    environment:
      - PORT=8080
    command: ["server"]
    depends_on:
      db:
        condition: service_healthy

  server3:
    build: .
    ports:
      - "8083:8080"
    environment:
      - PORT=8080
    command: ["server"]
    depends_on:
      db:
        condition: service_healthy

  balancer:
    build: .
    ports:
      - "8090:8090"
    depends_on:
      - server1
      - server2
      - server3
    command: ["balancer", "-trace=true"]

volumes:
  db-data: